#!/usr/bin/env python3
"""
A Python script that lists all documents with name starting
by Holberton in the collection school.
"""

import pymongo


def find_holberton_schools(mongo_collection):
    """
    Retrieves documents from the specified MongoDB collection
    where the name starts with "Holberton".

    Args:
        mongo_collection: A PyMongo collection object.

    Returns:
        A list of school documents (dictionaries) with names
        starting with "Holberton".
    """
    db.school.find({"name": {$regex: / ^ Holberton/}})
